image: netflixoss/mantisapi:latest
#image: localhost:5001/netflixoss/mantisapi:latest

# Ports used by Mantis control plane
api_port: 7001
# add other ports here

# Only logs every y request
log_sample_rate: 0.0001

# Only trace every x call
trace_sample_rate: 0.0001

# The number of Pods serving requests
replicas: 1

# Resources
resources:
  limits:
    cpu: "2"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "512Mi"
