apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mantis-publisher-sample
    app.kubernetes.io/part-of: mantis
    app.kubernetes.io/component: mantis-publisher
  name: mantis-publisher-sample
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mantis-publisher-sample