image: 
  repository: hmittal-agent

# Ports used by Mantis control plane
api_port: 5050
metrics_port: 5005
# add other ports here

# Only logs every y request
log_sample_rate: 0.0001

# Only trace every x call
trace_sample_rate: 0.0001

# The number of Pods serving requests
replicas: 3

# Resources
resources:
  limits:
    cpu: "2"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "512Mi"
