image: netflixoss/mantisagent:latest
#image: localhost:5001/netflixoss/mantisagent:latest

# Ports used by Mantis control plane
api_port: 5050
metrics_port: 5005
sink_port: 5054
# add other ports here

# Only logs every y request
log_sample_rate: 0.0001

# Only trace every x call
trace_sample_rate: 0.0001

# The number of Pods serving requests
replicas: 2

# Resources
resources:
  limits:
    cpu: "2"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "512Mi"
