zookeeper:
  fullnameOverride: zookeeper
  image:
    registry: docker.io
    repository: bitnamilegacy/zookeeper
    tag: "3.8.2-debian-11-r21"

mantis:
  ## kubernetes cluster domain name
  ## - configured in the kubelet with `--cluster-domain` flag (deprecated):
  ##   https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
  ## - or configured in the kubelet with configuration file `clusterDomain` option:
  ##   https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
  ##
  clusterDomain: "cluster.local"

  ######################################
  ## COMPONENT | Mantis Sample Publisher
  ######################################
  samplePublisher:
    ## if the publisher sample deployment should be created
    ##
    enabled: true
    # TODO: Using :latest once we cut of the official release
    image: netflixoss/mantis-publisher-sample:4.0.2-rc.3
